config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'admin' => 'admin#index'
  get 'question' => 'questions#index'
  get 'contact' => 'contacts#index'
  get 'warning' => 'warnings#index'

  resources :products do
    resources :comments
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    resources :comments
    root 'store#index', as: 'store'
  end

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string
#  score      :integer
#  body       :text
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :product
  validates :name, presence: true
  validates :body, presence: true
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#  order_id   :integer
#

class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :text
#  email      :string
#  pay_type   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  PAYMENT_TYPES = ["銀行振り込み", "クレジットカード", "コンビニ払い", "代金引換"]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  genre       :string
#  detail      :string
#

class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments, dependent: :destroy
  SCORE = ['1','2','3','4','5','6','7','8','9','10']

  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'はGIF・JPG・PNG画像のURLじゃないといかんバイ'
  }

  validates :title, length: {
    minimum: 1,
    message: "%{count}文字以上で入力せんと！！"
  }

  private

  # この商品を参照している品目がないことを確認する
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, "品目があるよ～ん")
      return false
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "最後のユーザは削除できんバイ！"
    end
  end
end

app/models/warning.rb
class Warning < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: :show
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @cart = Cart.find(session[:cart_id])
    @product = Product.find(params[:id])
    @comment = Product.find(params[:id]).comments.build
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: '項目は正常に作成されたバイ' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: '項目は正常に更新されたバイ' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '項目は正常に削除されたバイ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/aburas_helper.rb
module AburasHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/buyos_helper.rb
module BuyosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dosans_helper.rb
module DosansHelper
end

app/helpers/dragons_helper.rb
module DragonsHelper
end

app/helpers/ffs_helper.rb
module FfsHelper
end

app/helpers/kuradeus_helper.rb
module KuradeusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wes_helper.rb
module WesHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= link_to '参照', @product %> |
  
<% end %>

app/views/products/edit.html.erb
<h1>項目編集</h1>

<%= render 'form' %>

<%= link_to '参照', @product %> |
<%= link_to '戻る', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>項目参照</h1>

<table>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= image_tag(product.image_url, class: 'list_image') %></td>
        <td class="list_description">
          <dl>
            <dt><%= product.title %></dt>
            <dd><%= truncate(strip_tags(product.description), length: 75) %>
            </dd>
          </dl>
        </td>

        <td class="list_actions">
          <%= link_to '参照', product %><br>
          <%= link_to '編集', edit_product_path(product) %><br>
          <%= link_to '破壊', product, method: :delete, data: { confirm: '本当に良かと？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規商品追加', new_product_path %>



<%= link_to "新規作成", new_product_path %>
  <%= flash.notice %>
  <%= flash.alert %>
<hr>
<% @product.each do |f| %>
    <ul>
      タイトル：<%= link_to f.title, product_path(f)%>
    </ul>
    <ul>
      名前：<%= f.name %>
    </ul>
    <ul>
      点数：<%= f.score %>
    </ul>
    <ul><br>本文：</br>
      <%= simple_format(truncate(f.content,:length => 1000)) %>
    </ul>
    <ul>
      作成日時：<%= f.created_at.strftime("%Y/%m月%d日(#{%w(日 月 火 水 木 金 土 日)[Time.now.wday]})") %>
    </ul>
    <ul>
      <%= link_to "編集", edit_product_path(f) %>&nbsp;：&nbsp;<%= link_to "削除", f,
    :confirm => "削除してよろしいですか？",
    :method => :delete %>
    </ul>
    <ol>
    <% f.comments.each do |comment| %>
      <li>名前：<%= comment.name %>
          <%= comment.created_at.present? ? comment.created_at.strftime("%Y/%m月/%d日(#{%w(日 月 火 水 木 金 土 日)[Time.now.wday]}) %T ") : comment.created_at %>
      </li>
      <%= simple_format(comment.body) %>
    <% end %>
    </ol>
    <hr>

<% end %>

app/views/products/new.html.erb
<h1>新規商品作成</h1>

<%= render 'form' %>

<%= link_to '戻る', products_path %>

app/views/products/show.html.erb
<p>
  商品名:
  <strong><%= @product.title %></strong><br>
  <% if @product.comments.sum(:score) == 0 %>
  評価平均点：まだ評価されとらんバイ(><)
  <% else %>
  評価平均点：<strong><%= (@product.comments.sum(:score).to_f / @product.comments.count).round(1) %></strong>点(10点満点)
  <% end %>
</p>

<%= image_tag(@product.image_url) %>
<%= sanitize(@product.description) %>

<p>
  価格:
  <strong><%= number_to_currency(@product.price) %></strong>
</p>

<%= button_to '買い物籠に入れる', line_items_path(product_id: @product), remote: true %>

<%= link_to '編集', edit_product_path(@product) %> |
<%= link_to '戻る', store_path %>

<p>
<strong>ゲームの特徴：<br>
<%= sanitize(@product.detail) %></strong>
</p>
<br><br><br><br><br>

<div>

<%= flash.notice %>
<%= render "comments/form" %>