config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'admin' => 'admin#index'
  get 'question' => 'questions#index'
  get 'contact' => 'contacts#index'
  get 'warning' => 'warnings#index'

  resources :products do
    resources :comments
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products
    resources :comments
    root 'store#index', as: 'store'
  end

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string
#  score      :integer
#  body       :text
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :product
  validates :name, presence: true
  validates :body, presence: true
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#  order_id   :integer
#

class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :text
#  email      :string
#  pay_type   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  PAYMENT_TYPES = ["銀行振り込み", "クレジットカード", "コンビニ払い", "代金引換"]
  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  genre       :string
#  detail      :string
#

class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments, dependent: :destroy
  SCORE = ['1','2','3','4','5','6','7','8','9','10']

  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'はGIF・JPG・PNG画像のURLじゃないといかんバイ'
  }

  validates :title, length: {
    minimum: 1,
    message: "%{count}文字以上で入力せんと！！"
  }

  private

  # この商品を参照している品目がないことを確認する
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, "品目があるよ～ん")
      return false
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "最後のユーザは削除できんバイ！"
    end
  end
end

app/models/warning.rb
class Warning < ActiveRecord::Base
end

app/helpers/aburas_helper.rb
module AburasHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/buyos_helper.rb
module BuyosHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dosans_helper.rb
module DosansHelper
end

app/helpers/dragons_helper.rb
module DragonsHelper
end

app/helpers/ffs_helper.rb
module FfsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wes_helper.rb
module WesHelper
end

app/views/admin/index.html.erb
<h1>ようこそ</h1>

<p>現在の時刻は、<%= Time.zone.now.strftime("%Y年%m月%d日 %H:%M:%S") %>バイ。</p>
<p>今<%= @total_orders %>件の注文ば受付とるバイ。</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>GAME Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
<!--   <%= form_tag store_path, class: 'locale', method: :get do %>
    <%= select_tag 'set_locale',
      options_for_select(LANGUAGES, I18n.locale.to_s),
      onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
  <% end %>
 -->    
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <div id="cart">
        <%= render @cart %>
      </div>

      <ul>
        <li><%= link_to '最初の画面', store_path %></li>
        <li><%= link_to '良くある質問', question_path %></li>
        <li><%= link_to 'お問い合わせ', contact_path %></li>
        <li><a><%= @time %></a></li>
      </ul>
      <% if session[:user_id] %>
        <ul>
            <li><%= link_to '注文', orders_path %></li>
            <li><%= link_to '商品', products_path %></li>
            <li><%= link_to '管理者', users_path %></li>
        </ul>
        <%= button_to '退出', logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/order_notifier/received.html.erb
<h1>Dear <%= @order.name %></h1>

<p>GAME Jungleでのご注文、誠にありがとうございます。</p>

<p>ご注文されたのは以下の品目です。</p>

<%#= render @order.line_items %>
<ul>
  <% @order.line_items.each do |line_item| %>
    <li><%= sprintf("%2d x %s",
                line_item.quantity,
                truncate(line_item.product.title, length: 50)) %></li>
  <% end %>
</ul>
<p>ご注文の商品を発送する際には、別途電子メールでご連絡いたします。</p>


app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

GAME Jungleでのご注文、誠にありがとうございます。

ご注文されたのは以下の品目です。

<%#= render @order.line_items %>
<% @order.line_items.each do |line_item| %>
  <%= sprintf("%2d x %s",
              line_item.quantity,
              truncate(line_item.product.title, length: 50)) %>
<% end %>

ご注文の商品を発送する際には、別途電子メールでご連絡いたします。


app/views/order_notifier/shipped.html.erb
<h1>OrderNotifier#shipped</h1>

<p>
  <%= @greeting %>, find me in app/views/order_notifier/shipped.html.erb
</p>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb